# 💰 Ultra SIEM Funding & Sponsorship

# GitHub Sponsors
github: [YASSER-MN]

# Open Collective
open_collective: ultra-siem

# Additional sponsorship platforms
patreon: ultra-siem
ko_fi: ultra-siem

# Custom funding options
custom:
  - "https://ultra-siem.com/sponsor"
