# 💰 Ultra SIEM Funding & Sponsorship

# GitHub Sponsors
github: [ultra-siem]

# Open Collective
open_collective: ultra-siem

# Additional sponsorship platforms
patreon: ultra-siem
ko_fi: ultra-siem

# Custom funding options
custom:
  [
    "https://ultra-siem.com/sponsor",
    "https://opencollective.com/ultra-siem",
    "mailto:sponsor@ultra-siem.com",
  ]
