# 💰 Ultra SIEM Funding & Sponsorship

# Open Collective
open_collective: ultra-siem

# Additional sponsorship platforms
patreon: YasserMounim
ko_fi: yassermounim

# Custom funding options
custom:
  - "mailto:yassermn238@gmail.com?subject=Ultra%20SIEM%20Sponsorship"
