apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: https://clickhouse.example.com:8443
    user: ultra_siem
    secureJsonData:
      password: changeme
    jsonData:
      tlsSkipVerify: false
      defaultDatabase: siem
      timeInterval: 1s
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 300
    isDefault: true
    editable: false
