apiVersion: 1

datasources:
  - name: ClickHouse-SIEM
    type: clickhouse
    access: proxy
    url: http://clickhouse:8123
    database: siem
    user: grafana
    secureJsonData:
      password: ultra_secure_grafana_ch_2024
    jsonData:
      defaultDatabase: siem
      queryTimeout: 60s
      dialTimeout: 10s
      httpHeaders:
        - name: "X-ClickHouse-Format"
          value: "JSONCompact"
    isDefault: true
    editable: false
