apiVersion: 1

datasources:
  - name: ClickHouse-SIEM
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://host.docker.internal:8123
    isDefault: true
    jsonData:
      defaultDatabase: siem
      username: admin
      password: admin123
      protocol: http
      port: 8123
      host: host.docker.internal
    secureJsonData:
      password: admin123
    editable: true

  - name: ClickHouse-HTTP
    type: prometheus # Using Prometheus type as backup
    access: proxy
    url: http://host.docker.internal:8123
    isDefault: false
    jsonData:
      httpMethod: POST
    editable: true

  - name: TestData
    type: testdata
    access: proxy
    isDefault: false
    editable: true
