global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ultra-siem-rust-core"
    static_configs:
      - targets: ["rust-core:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "ultra-siem-go-bridge"
    static_configs:
      - targets: ["go-bridge:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse:8123"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "nats"
    static_configs:
      - targets: ["nats:8222"]
    metrics_path: "/varz"
    scrape_interval: 15s
